2023-12-12 20:33:22.714 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration breaking_changes which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:22.720 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration plex_recently_added which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:22.722 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration manish which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:22.725 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration plex_assistant which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:22.727 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration anniversaries which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:22.730 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ourgroceries which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:22.732 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration average which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:22.735 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration afvalinfo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:22.737 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration car_wash which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:22.739 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration saver which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:22.741 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration buienalarm which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:22.743 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:22.745 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration favicon which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:22.748 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration temperature_feels_like which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:22.750 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration illuminance which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:22.752 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hpprinter which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:22.759 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration fontawesome which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:22.761 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration pyscript which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:22.764 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration simpleicons which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:22.767 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration google_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:22.770 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration afvalbeheer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:22.772 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration worlds_air_quality_index which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:22.774 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration knmi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:22.776 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration google_photos which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:22.778 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration n26 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:22.778 ERROR (SyncWorker_0) [homeassistant.loader] The custom integration 'n26' does not have a version key in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details
2023-12-12 20:33:22.781 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration whatspie which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:22.784 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration lg_hombot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:22.787 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration pollenprognos which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:22.789 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration jokes which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:22.791 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration auto_backup which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:22.794 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration spotcast which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-12 20:33:44.250 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.vacuum.hombot.attributes.battery_icon }}'
2023-12-12 20:33:48.334 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'last_changed' when rendering 'last_changed: {{states.sensor.neerslag_buienalarm_regen_data.last_changed}}'
2023-12-12 20:33:48.435 ERROR (SyncWorker_6) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 20:33:48.437 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 20:34:22.689 WARNING (SyncWorker_9) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.69.103'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2023-12-12 20:34:22.888 WARNING (SyncWorker_9) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.69.103'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2023-12-12 20:34:24.365 ERROR (SyncWorker_6) [glocaltokens.client] [!] Could not get access token.
2023-12-12 20:34:24.973 WARNING (SyncWorker_3) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.69.103'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2023-12-12 20:34:25.005 WARNING (SyncWorker_5) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.69.103'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2023-12-12 20:34:25.083 WARNING (SyncWorker_4) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.69.103'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2023-12-12 20:34:25.091 WARNING (SyncWorker_4) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.69.103'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2023-12-12 20:34:25.167 WARNING (SyncWorker_5) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.69.103'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2023-12-12 20:34:27.364 WARNING (SyncWorker_6) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.69.103'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2023-12-12 20:34:27.371 WARNING (SyncWorker_6) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.69.103'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2023-12-12 20:34:42.263 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: mqtt
2023-12-12 20:34:48.063 WARNING (SyncWorker_1) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.69.103'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2023-12-12 20:34:48.081 WARNING (SyncWorker_1) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.69.103'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2023-12-12 20:34:48.100 WARNING (SyncWorker_1) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.69.103'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2023-12-12 20:34:48.109 WARNING (SyncWorker_1) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.69.103'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2023-12-12 20:34:48.136 WARNING (SyncWorker_1) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.69.103'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2023-12-12 20:34:48.338 WARNING (SyncWorker_1) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.69.103'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2023-12-12 20:34:48.360 WARNING (SyncWorker_1) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.69.103'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2023-12-12 20:34:48.369 WARNING (SyncWorker_1) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.69.103'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2023-12-12 20:34:48.387 WARNING (SyncWorker_1) [py.warnings] /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.69.103'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2023-12-12 20:34:49.583 ERROR (MainThread) [homeassistant.helpers.integration_platform] Error processing platform plex_assistant.intent
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 61, in _async_process_single_integration_platform_component
    await integration_platform.process_platform(hass, component_name, platform)
  File "/usr/src/homeassistant/homeassistant/components/intent/__init__.py", line 254, in _async_process_intent
    await platform.async_setup_intents(hass)
  File "/config/custom_components/plex_assistant/intent.py", line 9, in async_setup_intents
    hass.components.conversation.async_register(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in __getattr__
    value = getattr(self._module, attr)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'homeassistant.components.conversation' has no attribute 'async_register'
2023-12-12 20:34:58.669 WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform dlna_dmr is taking over 10 seconds.
2023-12-12 20:34:58.852 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ (states.sensor.desk_light_button_device_temperature.state | float - 8 ) | round(0) }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1926, in forgiving_float_filter
    return float(value)
           ^^^^^^^^^^^^
ValueError: could not convert string to float: 'unavailable'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 569, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2247, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1929, in forgiving_float_filter
    raise_no_default("float", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1627, in raise_no_default
    raise ValueError(
ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states.sensor.desk_light_button_device_temperature.state | float - 8 ) | round(0) }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 695, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 571, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states.sensor.desk_light_button_device_temperature.state | float - 8 ) | round(0) }}' but no default was specified
2023-12-12 20:34:58.873 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states.sensor.desk_light_button_device_temperature.state | float - 8 ) | round(0) }}' but no default was specified') while processing template 'Template<template=({{ (states.sensor.desk_light_button_device_temperature.state | float - 8 ) | round(0) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.desk_temp_adj'
2023-12-12 20:34:58.875 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ (states.sensor.front_door_sensor_device_temperature.state | float - 3 ) | round(0) }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1926, in forgiving_float_filter
    return float(value)
           ^^^^^^^^^^^^
ValueError: could not convert string to float: 'unavailable'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 569, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2247, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1929, in forgiving_float_filter
    raise_no_default("float", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1627, in raise_no_default
    raise ValueError(
ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states.sensor.front_door_sensor_device_temperature.state | float - 3 ) | round(0) }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 695, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 571, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states.sensor.front_door_sensor_device_temperature.state | float - 3 ) | round(0) }}' but no default was specified
2023-12-12 20:34:58.884 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states.sensor.front_door_sensor_device_temperature.state | float - 3 ) | round(0) }}' but no default was specified') while processing template 'Template<template=({{ (states.sensor.front_door_sensor_device_temperature.state | float - 3 ) | round(0) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.front_door_sensor_device_temperature_adj'
2023-12-12 20:34:58.886 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ (states.sensor.living_room_window_sensor_device_temperature.state | float - 4 ) | round(0) }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1926, in forgiving_float_filter
    return float(value)
           ^^^^^^^^^^^^
ValueError: could not convert string to float: 'unavailable'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 569, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2247, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1929, in forgiving_float_filter
    raise_no_default("float", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1627, in raise_no_default
    raise ValueError(
ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states.sensor.living_room_window_sensor_device_temperature.state | float - 4 ) | round(0) }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 695, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 571, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states.sensor.living_room_window_sensor_device_temperature.state | float - 4 ) | round(0) }}' but no default was specified
2023-12-12 20:34:58.898 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states.sensor.living_room_window_sensor_device_temperature.state | float - 4 ) | round(0) }}' but no default was specified') while processing template 'Template<template=({{ (states.sensor.living_room_window_sensor_device_temperature.state | float - 4 ) | round(0) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.living_room_window_sensor_device_temperature_adj'
2023-12-12 20:34:58.900 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.vacuum.hombot.attributes.battery_level }}'
2023-12-12 20:34:58.900 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ states.vacuum.hombot.attributes.battery_level }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 569, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2247, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.11/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2282, in _fail_with_undefined_error
    raise ex
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2279, in _fail_with_undefined_error
    return super()._fail_with_undefined_error(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'None' has no attribute 'attributes'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 695, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 571, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: UndefinedError: 'None' has no attribute 'attributes'
2023-12-12 20:34:58.911 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.vacuum.hombot.attributes.battery_icon }}'
2023-12-12 20:34:58.912 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ states.vacuum.hombot.attributes.battery_icon }}) renders=3>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 569, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2247, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.11/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2282, in _fail_with_undefined_error
    raise ex
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2279, in _fail_with_undefined_error
    return super()._fail_with_undefined_error(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'None' has no attribute 'attributes'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 695, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 571, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: UndefinedError: 'None' has no attribute 'attributes'
2023-12-12 20:34:58.922 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.vacuum.hombot.attributes.battery_level }}'
2023-12-12 20:34:58.923 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.vacuum.hombot.attributes.battery_icon }}'
2023-12-12 20:34:58.923 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: 'None' has no attribute 'attributes'') while processing template 'Template<template=({{ states.vacuum.hombot.attributes.battery_level }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.hombot_battery'
2023-12-12 20:34:58.924 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: 'None' has no attribute 'attributes'') while processing template 'Template<template=({{ states.vacuum.hombot.attributes.battery_icon }}) renders=5>' for attribute '_attr_icon' in entity 'sensor.hombot_battery'
2023-12-12 20:34:58.925 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.vacuum.hombot.attributes.status }}'
2023-12-12 20:34:58.927 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ states.vacuum.hombot.attributes.status }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 569, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2247, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.11/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2282, in _fail_with_undefined_error
    raise ex
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2279, in _fail_with_undefined_error
    return super()._fail_with_undefined_error(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'None' has no attribute 'attributes'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 695, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 571, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: UndefinedError: 'None' has no attribute 'attributes'
2023-12-12 20:34:58.937 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.vacuum.hombot.attributes.status }}'
2023-12-12 20:34:58.937 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: 'None' has no attribute 'attributes'') while processing template 'Template<template=({{ states.vacuum.hombot.attributes.status }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.hombot_status'
2023-12-12 20:34:58.944 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({% if states('sensor.medicine_hours_recent')|int > 23 %}
  {% set hours = states('sensor.medicine_hours_recent')|int - 24 %}
{% else %}
  {% set hours = states('sensor.medicine_hours_recent')|int %}
{% endif %}
  {% set minutes = states('sensor.medicine_minutes_recent')|int %}
{{hours|string + ":" + minutes|string }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 569, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2247, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1945, in forgiving_int_filter
    raise_no_default("int", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1627, in raise_no_default
    raise ValueError(
ValueError: Template error: int got invalid input 'unknown' when rendering template '{% if states('sensor.medicine_hours_recent')|int > 23 %}
  {% set hours = states('sensor.medicine_hours_recent')|int - 24 %}
{% else %}
  {% set hours = states('sensor.medicine_hours_recent')|int %}
{% endif %}
  {% set minutes = states('sensor.medicine_minutes_recent')|int %}
{{hours|string + ":" + minutes|string }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 695, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 571, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: int got invalid input 'unknown' when rendering template '{% if states('sensor.medicine_hours_recent')|int > 23 %}
  {% set hours = states('sensor.medicine_hours_recent')|int - 24 %}
{% else %}
  {% set hours = states('sensor.medicine_hours_recent')|int %}
{% endif %}
  {% set minutes = states('sensor.medicine_minutes_recent')|int %}
{{hours|string + ":" + minutes|string }}' but no default was specified
2023-12-12 20:34:58.955 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: int got invalid input 'unknown' when rendering template '{% if states('sensor.medicine_hours_recent')|int > 23 %}
  {% set hours = states('sensor.medicine_hours_recent')|int - 24 %}
{% else %}
  {% set hours = states('sensor.medicine_hours_recent')|int %}
{% endif %}
  {% set minutes = states('sensor.medicine_minutes_recent')|int %}
{{hours|string + ":" + minutes|string }}' but no default was specified') while processing template 'Template<template=({% if states('sensor.medicine_hours_recent')|int > 23 %}
  {% set hours = states('sensor.medicine_hours_recent')|int - 24 %}
{% else %}
  {% set hours = states('sensor.medicine_hours_recent')|int %}
{% endif %}
  {% set minutes = states('sensor.medicine_minutes_recent')|int %}
{{hours|string + ":" + minutes|string }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.medicine_time_recent'
2023-12-12 20:34:59.088 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error initializing 'Living rooms - lights on when blinds close' trigger: In 'numeric_state' condition: entity cover.living_room_blinds state 'closed' cannot be processed as a number
2023-12-12 20:34:59.091 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error initializing 'Bedroom - lights off when blinds open' trigger: In 'numeric_state' condition: entity cover.bedroom_blinds state 'closed' cannot be processed as a number
2023-12-12 20:35:03.931 WARNING (MainThread) [custom_components.hacs] You have 'ericpignet/home-assistant-lg_hombot' installed with HACS this repository has been removed from HACS, please consider removing it. Removal reason (Integration is missing a version, and is abandoned.)
2023-12-12 20:35:03.931 WARNING (MainThread) [custom_components.hacs] You have 'ljmerza/ha-our-groceries' installed with HACS this repository has been removed from HACS, please consider removing it. Removal reason (Repository is archived)
2023-12-12 20:35:09.300 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.home_precipitation (mm/h) cannot be converted to the unit of previously compiled statistics (mm). Generation of long term statistics will be suppressed unless the unit changes back to mm or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-12-12 20:35:09.304 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.openweathermap_rain (mm/h) cannot be converted to the unit of previously compiled statistics (mm). Generation of long term statistics will be suppressed unless the unit changes back to mm or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-12-12 20:35:09.305 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.openweathermap_snow (mm/h) cannot be converted to the unit of previously compiled statistics (mm). Generation of long term statistics will be suppressed unless the unit changes back to mm or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2023-12-12 20:35:34.494 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-12-12 20:35:34.497 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-12-12 20:35:34.499 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-12-12 20:35:34.883 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-12-12 20:35:34.886 ERROR (MainThread) [homeassistant.components.script.notify_people_who_are_present] Notify people who are home: If at step 2: Error executing script. Service not found for call_service at pos 1: Service notify.mobile_app_user2_phone not found.
2023-12-12 20:35:34.887 ERROR (MainThread) [homeassistant.components.script.notify_people_who_are_present] Notify people who are home: Error executing script. Service not found for if at pos 2: Service notify.mobile_app_user2_phone not found.
2023-12-12 20:35:34.888 ERROR (MainThread) [homeassistant.components.automation.all_rooms_rain_alert_when_window_open] All rooms - Rain alert when window open: If at step 4: Error executing script. Service not found for call_service at pos 1: Service notify.mobile_app_user2_phone not found.
2023-12-12 20:35:34.903 ERROR (MainThread) [homeassistant.components.automation.all_rooms_rain_alert_when_window_open] All rooms - Rain alert when window open: Error executing script. Service not found for if at pos 4: Service notify.mobile_app_user2_phone not found.
2023-12-12 20:35:34.932 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-12-12 20:35:34.934 ERROR (MainThread) [homeassistant.components.script.notify_people_who_are_present] Notify people who are home: If at step 2: Error executing script. Service not found for call_service at pos 1: Service notify.mobile_app_user2_phone not found.
2023-12-12 20:35:34.935 ERROR (MainThread) [homeassistant.components.script.notify_people_who_are_present] Notify people who are home: Error executing script. Service not found for if at pos 2: Service notify.mobile_app_user2_phone not found.
2023-12-12 20:35:34.938 ERROR (MainThread) [homeassistant.components.automation.all_rooms_rain_alert_when_window_open] All rooms - Rain alert when window open: If at step 4: Error executing script. Service not found for call_service at pos 1: Service notify.mobile_app_user2_phone not found.
2023-12-12 20:35:34.939 ERROR (MainThread) [homeassistant.components.automation.all_rooms_rain_alert_when_window_open] All rooms - Rain alert when window open: Error executing script. Service not found for if at pos 4: Service notify.mobile_app_user2_phone not found.
2023-12-12 20:35:34.967 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-12-12 20:35:34.970 ERROR (MainThread) [homeassistant.components.script.notify_people_who_are_present] Notify people who are home: If at step 2: Error executing script. Service not found for call_service at pos 1: Service notify.mobile_app_user2_phone not found.
2023-12-12 20:35:34.977 ERROR (MainThread) [homeassistant.components.script.notify_people_who_are_present] Notify people who are home: Error executing script. Service not found for if at pos 2: Service notify.mobile_app_user2_phone not found.
2023-12-12 20:35:34.983 ERROR (MainThread) [homeassistant.components.automation.all_rooms_rain_alert_when_window_open] All rooms - Rain alert when window open: If at step 4: Error executing script. Service not found for call_service at pos 1: Service notify.mobile_app_user2_phone not found.
2023-12-12 20:35:34.989 ERROR (MainThread) [homeassistant.components.automation.all_rooms_rain_alert_when_window_open] All rooms - Rain alert when window open: Error executing script. Service not found for if at pos 4: Service notify.mobile_app_user2_phone not found.
2023-12-12 20:36:34.423 WARNING (MainThread) [homeassistant.components.automation.hassio_control_washer_input_booleans_for_google] *HASSIO - Control washer input booleans for Google: Already running
2023-12-12 20:36:34.426 WARNING (MainThread) [homeassistant.components.automation.hassio_control_washer_input_booleans_for_google] *HASSIO - Control washer input booleans for Google: Already running
2023-12-12 20:37:49.463 ERROR (SyncWorker_2) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 20:37:49.465 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 20:38:34.467 WARNING (MainThread) [homeassistant.helpers.script] Error in 'if[0]' evaluation: In 'numeric_state':
  In 'numeric_state' condition: unknown entity sensor.humidity_11
2023-12-12 20:41:49.403 ERROR (SyncWorker_1) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 20:41:49.405 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 20:45:49.352 ERROR (SyncWorker_3) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 20:45:49.354 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 20:49:49.382 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 20:49:49.384 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 20:53:49.343 ERROR (SyncWorker_1) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 20:53:49.346 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 20:57:49.420 ERROR (SyncWorker_6) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 20:57:49.421 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 21:01:49.328 ERROR (SyncWorker_5) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 21:01:49.329 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 21:05:49.341 ERROR (SyncWorker_5) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 21:05:49.343 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 21:09:49.424 ERROR (SyncWorker_8) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 21:09:49.426 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 21:13:49.356 ERROR (SyncWorker_9) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 21:13:49.357 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 21:17:49.409 ERROR (SyncWorker_9) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 21:17:49.410 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 21:21:49.354 ERROR (SyncWorker_7) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 21:21:49.356 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 21:22:54.043 ERROR (MainThread) [frontend.js.latest.202312082] Uncaught error from WebKit 605.1.15 on iOS 17.2
TypeError: undefined is not an object (evaluating 'videojs__default["default"].createTimeRange')
/@videojs/http-streaming@2.16.0/dist/videojs-http-streaming.js:2541:51
/@videojs/http-streaming@2.16.0/dist/videojs-http-streaming.js:5:84
module code (/@videojs/http-streaming@2.16.0/dist/videojs-http-streaming.js:6:3)
2023-12-12 21:23:31.509 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.69.100 (192.168.69.100). Requested URL: '/api/websocket'. (Mozilla/5.0 (iPhone; CPU iPhone OS 17_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2023.7 (io.robbie.HomeAssistant; build:2023.471; iOS 17.2.0) Mobile/HomeAssistant, like Safari)
2023-12-12 21:23:31.515 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.69.100 (192.168.69.100). Requested URL: '/api/websocket'. (Home Assistant/2023.7 (io.robbie.HomeAssistant; build:2023.471; iOS 17.2.0))
2023-12-12 21:23:31.558 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.69.100 (192.168.69.100). Requested URL: '/api/websocket'. (Home Assistant/2023.7 (io.robbie.HomeAssistant; build:2023.471; iOS 17.2.0))
2023-12-12 21:23:31.593 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.69.100 (192.168.69.100). Requested URL: '/api/websocket'. (Home Assistant/2023.7 (io.robbie.HomeAssistant; build:2023.471; iOS 17.2.0))
2023-12-12 21:23:31.729 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.69.100 (192.168.69.100). Requested URL: '/api/websocket'. (Mozilla/5.0 (iPhone; CPU iPhone OS 17_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2023.7 (io.robbie.HomeAssistant; build:2023.471; iOS 17.2.0) Mobile/HomeAssistant, like Safari)
2023-12-12 21:23:31.827 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.69.100 (192.168.69.100). Requested URL: '/auth/token'. (Home Assistant/2023.7 (io.robbie.HomeAssistant; build:2023.471; iOS 17.2.0) Alamofire/5.6.4)
2023-12-12 21:23:36.833 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.69.100 (192.168.69.100). Requested URL: '/auth/token'. (Home Assistant/2023.7 (io.robbie.HomeAssistant; build:2023.471; iOS 17.2.0) Alamofire/5.6.4)
2023-12-12 21:23:47.007 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.69.100 (192.168.69.100). Requested URL: '/auth/token'. (Home Assistant/2023.7 (io.robbie.HomeAssistant; build:2023.471; iOS 17.2.0) Alamofire/5.6.4)
2023-12-12 21:23:57.191 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.69.100 (192.168.69.100). Requested URL: '/auth/token'. (Home Assistant/2023.7 (io.robbie.HomeAssistant; build:2023.471; iOS 17.2.0) Alamofire/5.6.4)
2023-12-12 21:24:06.924 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [547533491264] from 192.168.69.100 (Home Assistant/2023.7 (io.robbie.HomeAssistant; build:2023.471; iOS 17.2.0)): Disconnected: Did not receive auth message within 10 seconds
2023-12-12 21:24:12.402 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.69.100 (192.168.69.100). Requested URL: '/auth/token'. (Home Assistant/2023.7 (io.robbie.HomeAssistant; build:2023.471; iOS 17.2.0) Alamofire/5.6.4)
2023-12-12 21:24:17.113 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [547533498048] from 192.168.69.100 (Home Assistant/2023.7 (io.robbie.HomeAssistant; build:2023.471; iOS 17.2.0)): Disconnected: Did not receive auth message within 10 seconds
2023-12-12 21:24:24.901 ERROR (MainThread) [frontend.js.latest.202312082] Uncaught error from WebKit 605.1.15 on iOS 17.2
TypeError: undefined is not an object (evaluating 'videojs__default["default"].createTimeRange')
/@videojs/http-streaming@2.16.0/dist/videojs-http-streaming.js:2541:51
/@videojs/http-streaming@2.16.0/dist/videojs-http-streaming.js:5:84
module code (/@videojs/http-streaming@2.16.0/dist/videojs-http-streaming.js:6:3)
2023-12-12 21:24:32.302 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [547533883456] from 192.168.69.100 (Home Assistant/2023.7 (io.robbie.HomeAssistant; build:2023.471; iOS 17.2.0)): Disconnected: Did not receive auth message within 10 seconds
2023-12-12 21:25:49.452 ERROR (SyncWorker_9) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 21:25:49.453 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 21:26:04.897 ERROR (MainThread) [frontend.js.latest.202312082] Uncaught error from WebKit 605.1.15 on iOS 17.2
TypeError: undefined is not an object (evaluating 'videojs__default["default"].createTimeRange')
/@videojs/http-streaming@2.16.0/dist/videojs-http-streaming.js:2541:51
/@videojs/http-streaming@2.16.0/dist/videojs-http-streaming.js:5:84
module code (/@videojs/http-streaming@2.16.0/dist/videojs-http-streaming.js:6:3)
2023-12-12 21:29:49.385 ERROR (SyncWorker_9) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 21:29:49.387 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 21:33:49.355 ERROR (SyncWorker_8) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 21:33:49.357 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 21:34:57.283 WARNING (MainThread) [homeassistant.helpers.script] Error in 'if[0]' evaluation: In 'numeric_state':
  In 'numeric_state' condition: unknown entity sensor.humidity_11
2023-12-12 21:37:49.426 ERROR (SyncWorker_9) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 21:37:49.429 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 21:39:03.026 ERROR (MainThread) [homeassistant.components.oralb] F8:8A:5E:E5:61:CC: Bluetooth error whilst polling: F8:8A:5E:E5:61:CC - F8:8A:5E:E5:61:CC: Failed to connect after 4 attempt(s): TimeoutError
2023-12-12 21:41:49.387 ERROR (SyncWorker_0) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 21:41:49.389 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 21:45:49.320 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 21:45:49.322 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 21:49:49.504 ERROR (SyncWorker_1) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 21:49:49.506 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 21:53:49.319 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 21:53:49.321 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 21:57:49.424 ERROR (SyncWorker_7) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 21:57:49.426 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 22:01:49.282 ERROR (SyncWorker_1) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 22:01:49.284 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 22:05:49.411 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 22:05:49.412 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 22:08:42.306 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-12-12 22:08:42.664 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-12-12 22:08:42.667 ERROR (MainThread) [homeassistant.components.script.notify_people_who_are_present] Notify people who are home: If at step 2: Error executing script. Service not found for call_service at pos 1: Service notify.mobile_app_user2_phone not found.
2023-12-12 22:08:42.669 ERROR (MainThread) [homeassistant.components.script.notify_people_who_are_present] Notify people who are home: Error executing script. Service not found for if at pos 2: Service notify.mobile_app_user2_phone not found.
2023-12-12 22:08:42.672 ERROR (MainThread) [homeassistant.components.automation.all_rooms_rain_alert_when_window_open] All rooms - Rain alert when window open: Error executing script. Service not found for call_service at pos 8: Service notify.mobile_app_user2_phone not found.
2023-12-12 22:09:49.314 ERROR (SyncWorker_7) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 22:09:49.316 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 22:13:49.334 ERROR (SyncWorker_3) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 22:13:49.336 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 22:17:49.395 ERROR (SyncWorker_6) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 22:17:49.397 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 22:21:49.328 ERROR (SyncWorker_0) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 22:21:49.329 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 22:25:49.391 ERROR (SyncWorker_0) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 22:25:49.393 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 22:29:49.335 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 22:29:49.337 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 22:33:49.349 ERROR (SyncWorker_9) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 22:33:49.351 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 22:37:49.386 ERROR (SyncWorker_6) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 22:37:49.388 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 22:41:49.451 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 22:41:49.452 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 22:43:22.890 ERROR (MainThread) [homeassistant.components.automation.hassio_medicine_reminder] *HASSIO - Medicine reminder: Choose at step 1: choice 1: Error executing script. Service not found for call_service at pos 2: Service notify.mobile_app_user2_phone not found.
2023-12-12 22:43:22.891 ERROR (MainThread) [homeassistant.components.automation.hassio_medicine_reminder] *HASSIO - Medicine reminder: Error executing script. Service not found for choose at pos 1: Service notify.mobile_app_user2_phone not found.
2023-12-12 22:45:49.333 ERROR (SyncWorker_1) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 22:45:49.335 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 22:46:06.266 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-12-12 22:46:06.623 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-12-12 22:46:06.626 ERROR (MainThread) [homeassistant.components.script.notify_people_who_are_present] Notify people who are home: If at step 2: Error executing script. Service not found for call_service at pos 1: Service notify.mobile_app_user2_phone not found.
2023-12-12 22:46:06.627 ERROR (MainThread) [homeassistant.components.script.notify_people_who_are_present] Notify people who are home: Error executing script. Service not found for if at pos 2: Service notify.mobile_app_user2_phone not found.
2023-12-12 22:46:06.631 ERROR (MainThread) [homeassistant.components.automation.all_rooms_rain_alert_when_window_open] All rooms - Rain alert when window open: If at step 4: Error executing script. Service not found for call_service at pos 1: Service notify.mobile_app_user2_phone not found.
2023-12-12 22:46:06.631 ERROR (MainThread) [homeassistant.components.automation.all_rooms_rain_alert_when_window_open] All rooms - Rain alert when window open: Error executing script. Service not found for if at pos 4: Service notify.mobile_app_user2_phone not found.
2023-12-12 22:49:49.330 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 22:49:49.332 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 22:51:15.547 WARNING (MainThread) [homeassistant.helpers.script] Error in 'if[0]' evaluation: In 'numeric_state':
  In 'numeric_state' condition: unknown entity sensor.humidity_11
2023-12-12 22:53:49.469 ERROR (SyncWorker_7) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 22:53:49.471 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 22:57:49.357 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 22:57:49.358 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 23:01:49.330 ERROR (SyncWorker_0) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 23:01:49.331 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 23:05:49.320 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 23:05:49.322 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 23:09:20.905 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-12-12 23:09:49.421 ERROR (SyncWorker_1) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 23:09:49.423 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 23:12:05.837 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.tv_adb is taking over 10 seconds
2023-12-12 23:12:05.838 WARNING (MainThread) [homeassistant.components.media_player] Updating androidtv media_player took longer than the scheduled update interval 0:00:10
2023-12-12 23:13:49.335 ERROR (SyncWorker_3) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 23:13:49.336 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 23:13:51.499 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
2023-12-12 23:17:49.435 ERROR (SyncWorker_5) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 23:17:49.437 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 23:21:49.392 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 23:21:49.393 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 23:25:49.331 ERROR (SyncWorker_1) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 23:25:49.332 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 23:29:49.393 ERROR (SyncWorker_8) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 23:29:49.394 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 23:33:49.404 ERROR (SyncWorker_1) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 23:33:49.406 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 23:37:49.316 ERROR (SyncWorker_8) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 23:37:49.318 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 23:41:49.385 ERROR (SyncWorker_0) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 23:41:49.387 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 23:45:49.366 ERROR (SyncWorker_7) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 23:45:49.372 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 23:49:49.322 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 23:49:49.324 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 23:53:49.416 ERROR (SyncWorker_2) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 23:53:49.416 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-12 23:57:49.372 ERROR (SyncWorker_2) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-12 23:57:49.374 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 00:01:49.414 ERROR (SyncWorker_3) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 00:01:49.416 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 00:05:49.395 ERROR (SyncWorker_5) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 00:05:49.397 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 00:09:21.287 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-12-13 00:09:21.616 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-12-13 00:09:21.619 ERROR (MainThread) [homeassistant.components.script.notify_people_who_are_present] Notify people who are home: If at step 2: Error executing script. Service not found for call_service at pos 1: Service notify.mobile_app_user2_phone not found.
2023-12-13 00:09:21.620 ERROR (MainThread) [homeassistant.components.script.notify_people_who_are_present] Notify people who are home: Error executing script. Service not found for if at pos 2: Service notify.mobile_app_user2_phone not found.
2023-12-13 00:09:21.623 ERROR (MainThread) [homeassistant.components.automation.all_rooms_rain_alert_when_window_open] All rooms - Rain alert when window open: Error executing script. Service not found for call_service at pos 8: Service notify.mobile_app_user2_phone not found.
2023-12-13 00:09:49.408 ERROR (SyncWorker_1) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 00:09:49.410 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 00:13:49.355 ERROR (SyncWorker_3) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 00:13:49.356 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 00:16:36.624 WARNING (MainThread) [homeassistant.helpers.script] Error in 'if[0]' evaluation: In 'numeric_state':
  In 'numeric_state' condition: unknown entity sensor.humidity_11
2023-12-13 00:17:49.432 ERROR (SyncWorker_6) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 00:17:49.433 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 00:21:49.472 ERROR (SyncWorker_3) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 00:21:49.474 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 00:25:49.376 ERROR (SyncWorker_1) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 00:25:49.378 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 00:29:49.410 ERROR (SyncWorker_1) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 00:29:49.411 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 00:33:49.393 ERROR (SyncWorker_3) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 00:33:49.394 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 00:37:49.420 ERROR (SyncWorker_9) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 00:37:49.421 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 00:41:49.366 ERROR (SyncWorker_7) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 00:41:49.367 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 00:45:49.339 ERROR (SyncWorker_8) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 00:45:49.341 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 00:49:49.428 ERROR (SyncWorker_9) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 00:49:49.430 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 00:53:49.370 ERROR (SyncWorker_5) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 00:53:49.371 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 00:57:49.380 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 00:57:49.382 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 01:01:49.355 ERROR (SyncWorker_2) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 01:01:49.356 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 01:05:49.373 ERROR (SyncWorker_2) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 01:05:49.375 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 01:09:49.427 ERROR (SyncWorker_5) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 01:09:49.429 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 01:13:49.428 ERROR (SyncWorker_9) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 01:13:49.430 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 01:17:49.368 ERROR (SyncWorker_9) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 01:17:49.370 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 01:21:49.402 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 01:21:49.404 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 01:25:49.324 ERROR (SyncWorker_0) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 01:25:49.326 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 01:29:49.367 ERROR (SyncWorker_6) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 01:29:49.369 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 01:33:49.436 ERROR (SyncWorker_0) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 01:33:49.438 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 01:37:49.410 ERROR (SyncWorker_3) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 01:37:49.411 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 01:41:49.346 ERROR (SyncWorker_1) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 01:41:49.347 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 01:45:49.329 ERROR (SyncWorker_2) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 01:45:49.331 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 01:49:49.422 ERROR (SyncWorker_1) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 01:49:49.423 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 01:53:49.394 ERROR (SyncWorker_6) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 01:53:49.396 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 01:57:49.389 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 01:57:49.390 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 01:58:09.133 WARNING (MainThread) [homeassistant.helpers.script] Error in 'if[0]' evaluation: In 'numeric_state':
  In 'numeric_state' condition: unknown entity sensor.humidity_11
2023-12-13 02:01:49.349 ERROR (SyncWorker_8) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 02:01:49.350 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 02:05:49.362 ERROR (SyncWorker_3) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 02:05:49.363 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 02:09:26.469 WARNING (MainThread) [homeassistant.helpers.script] Error in 'if[0]' evaluation: In 'numeric_state':
  In 'numeric_state' condition: unknown entity sensor.humidity_11
2023-12-13 02:09:49.447 ERROR (SyncWorker_6) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 02:09:49.448 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 02:11:56.001 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities light.floor are missing or not currently available
2023-12-13 02:13:49.342 ERROR (SyncWorker_6) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 02:13:49.343 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 02:17:49.362 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 02:17:49.364 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 02:21:46.960 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.tv_adb is taking over 10 seconds
2023-12-13 02:21:46.960 WARNING (MainThread) [homeassistant.components.media_player] Updating androidtv media_player took longer than the scheduled update interval 0:00:10
2023-12-13 02:21:49.397 ERROR (SyncWorker_3) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 02:21:49.398 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 02:25:49.407 ERROR (SyncWorker_9) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 02:25:49.408 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 02:28:27.925 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities light.floor are missing or not currently available
2023-12-13 02:29:49.457 ERROR (SyncWorker_9) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 02:29:49.459 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 02:31:14.658 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities light.floor are missing or not currently available
2023-12-13 02:31:58.548 WARNING (MainThread) [homeassistant.components.media_player] Updating samsungtv media_player took longer than the scheduled update interval 0:00:10
2023-12-13 02:31:58.548 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.samsung_tv is taking over 10 seconds
2023-12-13 02:33:49.391 ERROR (SyncWorker_3) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 02:33:49.393 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 02:37:49.417 ERROR (SyncWorker_0) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 02:37:49.419 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 02:41:49.338 ERROR (SyncWorker_8) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 02:41:49.339 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 02:45:49.400 ERROR (SyncWorker_8) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 02:45:49.402 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 02:49:49.407 ERROR (SyncWorker_7) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 02:49:49.409 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 02:52:48.998 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities light.floor are missing or not currently available
2023-12-13 02:53:49.404 ERROR (SyncWorker_6) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 02:53:49.405 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 02:54:59.664 WARNING (Thread-10) [pychromecast.socket_client] [Living room(192.168.69.236):8009] Heartbeat timeout, resetting connection
2023-12-13 02:55:18.117 ERROR (Thread-10) [pychromecast.socket_client] [Living room(192.168.69.236):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.69.236', 8009)), retrying in 5.0s
2023-12-13 02:57:49.411 ERROR (SyncWorker_8) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 02:57:49.413 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 03:01:49.375 ERROR (SyncWorker_7) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 03:01:49.377 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 03:05:49.342 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 03:05:49.343 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 03:09:49.446 ERROR (SyncWorker_0) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 03:09:49.448 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 03:13:49.358 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 03:13:49.360 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 03:17:49.398 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 03:17:49.400 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 03:21:49.465 ERROR (SyncWorker_6) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 03:21:49.467 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 03:23:42.296 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-12-13 03:23:42.666 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'title' is undefined when rendering '{{ title }}'
2023-12-13 03:23:42.668 ERROR (MainThread) [homeassistant.components.script.notify_people_who_are_present] Notify people who are home: If at step 2: Error executing script. Service not found for call_service at pos 1: Service notify.mobile_app_user2_phone not found.
2023-12-13 03:23:42.669 ERROR (MainThread) [homeassistant.components.script.notify_people_who_are_present] Notify people who are home: Error executing script. Service not found for if at pos 2: Service notify.mobile_app_user2_phone not found.
2023-12-13 03:23:42.670 ERROR (MainThread) [homeassistant.components.automation.all_rooms_rain_alert_when_window_open] All rooms - Rain alert when window open: Error executing script. Service not found for call_service at pos 8: Service notify.mobile_app_user2_phone not found.
2023-12-13 03:25:49.332 ERROR (SyncWorker_6) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 03:25:49.334 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 03:29:49.390 ERROR (SyncWorker_5) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 03:29:49.391 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 03:33:49.423 ERROR (SyncWorker_3) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 03:33:49.424 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 03:37:49.410 ERROR (SyncWorker_7) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 03:37:49.412 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 03:41:49.378 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 03:41:49.380 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 03:45:49.385 ERROR (SyncWorker_3) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 03:45:49.387 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 03:49:49.476 ERROR (SyncWorker_1) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 03:49:49.478 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 03:53:49.399 ERROR (SyncWorker_1) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 03:53:49.400 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 03:57:49.485 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 03:57:49.487 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 04:01:25.094 ERROR (MainThread) [plexwebsocket] Websocket connection failed, retrying in 15s: Cannot connect to host 192.168.69.103:32400 ssl:False [Connect call failed ('192.168.69.103', 32400)]
2023-12-13 04:01:49.415 ERROR (SyncWorker_3) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 04:01:49.417 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 04:03:50.502 ERROR (MainThread) [plexwebsocket] Websocket connection failed, retrying in 30s: Cannot connect to host 192.168.69.103:32400 ssl:False [Connect call failed ('192.168.69.103', 32400)]
2023-12-13 04:04:19.070 ERROR (Thread-9) [pychromecast.socket_client] [Both rooms(192.168.69.113):32191] Error reading from socket.
2023-12-13 04:04:19.070 WARNING (Thread-9) [pychromecast.socket_client] [Both rooms(192.168.69.113):32191] Error communicating with socket, resetting connection
2023-12-13 04:04:19.085 ERROR (Thread-9) [pychromecast.socket_client] [Both rooms(192.168.69.113):32191] Failed to connect to service ServiceInfo(type='host', data=('192.168.69.113', 32191)), retrying in 5.0s
2023-12-13 04:04:36.322 WARNING (MainThread) [homeassistant.helpers.entity] Update of update.plex_media_server_deskjop is taking over 10 seconds
2023-12-13 04:04:44.142 WARNING (Thread-8) [pychromecast.socket_client] [Bedroom(192.168.69.113):8009] Heartbeat timeout, resetting connection
2023-12-13 04:04:57.376 ERROR (MainThread) [homeassistant.components.plex.server] Could not connect to Plex server: DeskJop (HTTPSConnectionPool(host='192.168.69.103', port=32400): Max retries exceeded with url: /clients (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f89e4ead0>, 'Connection to 192.168.69.103 timed out. (connect timeout=30)')))
2023-12-13 04:05:02.339 ERROR (Thread-8) [pychromecast.socket_client] [Bedroom(192.168.69.113):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.69.113', 8009)), retrying in 5.0s
2023-12-13 04:05:03.599 ERROR (Thread-9) [pychromecast.socket_client] [Both rooms(192.168.69.221):32190] Error reading from socket.
2023-12-13 04:05:03.599 WARNING (Thread-9) [pychromecast.socket_client] [Both rooms(192.168.69.221):32190] Error communicating with socket, resetting connection
2023-12-13 04:05:03.609 ERROR (Thread-9) [pychromecast.socket_client] [Both rooms(192.168.69.221):32190] Failed to connect to service ServiceInfo(type='mdns', data='Google-Cast-Group-7978343ab66e443db7e479c6dce645cc._googlecast._tcp.local.'), retrying in 5.0s
2023-12-13 04:05:49.387 ERROR (SyncWorker_0) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 04:05:49.388 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 04:06:30.246 ERROR (MainThread) [plexwebsocket] Websocket connection failed, retrying in 60s: Cannot connect to host 192.168.69.103:32400 ssl:False [Connect call failed ('192.168.69.103', 32400)]
2023-12-13 04:09:40.710 ERROR (MainThread) [plexwebsocket] Websocket connection failed, retrying in 120s: Cannot connect to host 192.168.69.103:32400 ssl:False [Connect call failed ('192.168.69.103', 32400)]
2023-12-13 04:09:49.426 ERROR (SyncWorker_5) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 04:09:49.428 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 04:13:49.404 ERROR (SyncWorker_9) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 04:13:49.406 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 04:13:50.566 ERROR (MainThread) [plexwebsocket] Websocket connection failed, retrying in 240s: Cannot connect to host 192.168.69.103:32400 ssl:False [Connect call failed ('192.168.69.103', 32400)]
2023-12-13 04:14:57.389 ERROR (MainThread) [homeassistant.components.plex.server] Could not connect to Plex server: DeskJop (HTTPSConnectionPool(host='192.168.69.103', port=32400): Max retries exceeded with url: /clients (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f7439e890>, 'Connection to 192.168.69.103 timed out. (connect timeout=30)')))
2023-12-13 04:17:49.416 ERROR (SyncWorker_5) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 04:17:49.418 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 04:18:09.374 WARNING (MainThread) [homeassistant.helpers.script] Error in 'if[0]' evaluation: In 'numeric_state':
  In 'numeric_state' condition: unknown entity sensor.humidity_11
2023-12-13 04:19:36.454 WARNING (MainThread) [homeassistant.helpers.entity] Update of update.plex_media_server_deskjop is taking over 10 seconds
2023-12-13 04:20:01.255 ERROR (MainThread) [homeassistant.components.plex] Websocket to DeskJop failed, aborting [Error: Too many retries]
2023-12-13 04:21:49.414 ERROR (SyncWorker_7) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 04:21:49.416 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 04:25:49.416 ERROR (SyncWorker_4) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 04:25:49.417 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 04:29:49.451 ERROR (SyncWorker_5) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 04:29:49.453 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 04:33:49.425 ERROR (SyncWorker_0) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 04:33:49.427 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 04:37:49.398 ERROR (SyncWorker_5) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 04:37:49.399 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 04:41:49.425 ERROR (SyncWorker_6) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 04:41:49.426 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 04:45:49.381 ERROR (SyncWorker_8) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 04:45:49.382 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 04:49:49.439 ERROR (SyncWorker_9) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 04:49:49.441 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 04:53:49.379 ERROR (SyncWorker_5) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 04:53:49.381 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
2023-12-13 04:57:49.414 ERROR (SyncWorker_7) [homeassistant.components.command_line.utils] Command failed (with return code 1): python3 -c "import requests; import json; import random; dataRequest = requests.get('https://gpsgadget.buienradar.nl/data/raintext?lat=51.83&lon=5.86&c='+str(random.randint(0,999999999999999)) ).text; dataRequest = dataRequest.replace('\r\n',' '); data = '{\"data\":\"'+dataRequest+'\"}';    pri(data);"
2023-12-13 04:57:49.415 WARNING (MainThread) [homeassistant.components.command_line] Empty reply found when expecting JSON data
